name: mlflow
channels:
  - conda-forge
  - defaults
dependencies:
  - alembic=0.9.5
  - appdirs=1.4.4
  - asn1crypto=1.4.0
  - azure-core=1.9.0
  - azure-storage-blob=12.6.0
  - blinker=1.4
  - brotlipy=0.7.0
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.6.0
  - configparser=5.0.1
  - cryptography=3.3.1
  - databricks-cli=0.9.1
  - docker-py=4.4.0
  - docker-pycreds=0.4.0
  - entrypoints=0.3
  - flask=1.1.2
  - gitdb=4.0.5
  - gitpython=3.1.11
  - gorilla=0.3.0
  - gunicorn=20.0.4
  - idna=2.10
  - isodate=0.6.0
  - itsdangerous=1.1.0
  - jinja2=2.11.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=11.0.0
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libprotobuf=3.14.0
  - llvm-openmp=11.0.0
  - mako=1.1.3
  - markupsafe=1.1.1
  - mlflow=1.12.1
  - msrest=0.6.19
  - ncurses=6.2
  - numpy=1.19.4
  - oauthlib=3.0.1
  - openssl=1.1.1i
  - packaging=20.7
  - pandas=1.1.5
  - pip=20.3.1
  - prometheus_client=0.9.0
  - prometheus_flask_exporter=0.18.1
  - protobuf=3.14.0
  - pycparser=2.20
  - pyjwt=1.7.1
  - pyopenssl=20.0.0
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.6.12
  - python-dateutil=2.8.1
  - python-editor=1.0.4
  - python_abi=3.6
  - pytz=2020.4
  - pyyaml=5.3.1
  - querystring_parser=1.2.4
  - readline=8.0
  - requests=2.25.0
  - requests-oauthlib=1.3.0
  - setuptools=49.6.0
  - six=1.15.0
  - smmap=3.0.4
  - sqlalchemy=1.3.20
  - sqlite=3.34.0
  - sqlparse=0.4.1
  - tabulate=0.8.7
  - tk=8.6.10
  - urllib3=1.25.11
  - websocket-client=0.57.0
  - werkzeug=1.0.1
  - wheel=0.36.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
